name: 001 - Test Workflow

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the app to test'
        required: true
        default: 'blogs'
        type: choice
        options:
          - blog
          - mehrlicht
          - lakmusz
          - qubit
          - 444hu

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Commit Status to Pending
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "pending", "context": "Test Workflow - ${{ inputs.app }}", "description": "Tests for ${{ inputs.app }} are running..."}'

      - name: Install Dependencies
        run: |
          echo "Installing dependencies for ${{ inputs.app }}"
          cd apps/${{ inputs.app }}
          # npm ci

      - name: Run Tests
        run: |
          echo "Running tests for ${{ inputs.app }}"
          cd apps/${{ inputs.app }}
          # npm run test
          echo "Tests passed successfully!"

      - name: Set Commit Status to Success
        if: ${{ success() }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "success", "context": "Test Workflow - ${{ inputs.app }}", "description": "Tests for ${{ inputs.app }} passed successfully!"}'

      - name: Set Commit Status to Failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state": "failure", "context": "Test Workflow - ${{ inputs.app }}", "description": "Tests for ${{ inputs.app }} failed."}'
