name: Google Cloud Run Deploy

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the app to deploy to Cloud Run'
        required: true
        default: 'blogs'
        type: choice
        options:
          - blog
          - mehrlicht
          - lakmusz
          - qubit
          - 444hu
      use_remote_cache:
        description: 'Enable TurboRepo remote cache (true/false)'
        required: false
        default: 'true'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v1
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}

      # - name: Configure Google Cloud
      #   run: |
      #     gcloud config set project ${{ secrets.GCP_PROJECT }}
      #     gcloud config set compute/region ${{ secrets.GCP_REGION }}

      - name: Build and Push Docker Image
        run: |
          # IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT }}/${{ inputs.app }}:${{ github.sha }}"
          IMAGE_NAME="debug"
          docker build -t $IMAGE_NAME \
            --build-arg USE_REMOTE_CACHE=${{ inputs.use_remote_cache }} \
            --build-arg TURBO_TOKEN=${{ secrets.TURBO_TOKEN }} \
            --build-arg TURBO_TEAM=${{ secrets.TURBO_TEAM }} \
            -f apps/${{ inputs.app }}/Dockerfile .
          gcloud auth configure-docker
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          SERVICE_NAME=${{ inputs.app }}-service
          gcloud run deploy $SERVICE_NAME \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ inputs.app }}:${{ github.sha }} \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --min-instances 1 \
            --max-instances 4 \
            --cpu 0.5 --memory 256Mi \
            --timeout=30s \
            --ingress internal \
            --allow-unauthenticated
