name: Vercel Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      application:
        description: 'Choose application to deploy'
        required: true
        type: choice
        options:
          - blog
          - mehrlicht
          - lakmusz
          - qubit
          - 444hu
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

      - name: Set Wildcard Alias
        run: |
          echo "🚀 Setting wildcard alias for ${{ github.event.inputs.application }}..."
          COMMIT_ID=$(git rev-parse --short HEAD)
          WILDCARD_SUBDOMAIN="${{ github.event.inputs.application }}.${COMMIT_ID}.vercel.jeti.dev"
          vercel alias set ${{ steps.vercel-deploy.outputs.deployment-url }} $WILDCARD_SUBDOMAIN --token=${{ secrets.VERCEL_TOKEN }}
          echo "✅ Alias set: https://${WILDCARD_SUBDOMAIN}"

      - name: Post Deployment Details
        if: success()
        run: |
          echo "🚀 Deployment successful for ${{ github.event.inputs.application }}."
          echo "🔗 Visit the app: https://${{ github.event.inputs.application }}.${{ github.sha }}.vercel.jeti.dev"
